import {
  Blogging,
  CompanyLogo1,
  Coursera,
  DiamondLgBlue,
  DiamondLgGreen,
  DiamondLgOrange,
  DiamondLgPink,
  DiamondLgYellow,
  Gaming,
  Google,
  Reading,
  SkillAsp,
  SkillBlazor,
  SkillBootstrap,
  SkillCss,
  SkillEntity,
  SkillHtml5,
  SkillJavaSpringBoot,
  SkillLaravel,
  SkillMicrosoftSQL,
  SkillPHPUnit,
  SkillPostgreSQL,
  SkillReact,
  SkillSelenium,
  SkillTailwind,
  SkillTrello,
  Travelling,
  Udemy,
} from "../assets/image";

const DATA = {
  professionalExperiences: [
    {
      id: "prof_exp_1",
      startDate: "Jun 2024",
      endDate: "Ian 2025",
      position: "Junior Web Developer",
      diamondColors: ["Purple", "Yellow", "Blue"],
      company: {
        logo: CompanyLogo1,
        name: "AMC WebSoft",
        info: "Custom website and software development in Craiova, Dolj",
      },
      description:
        "Created a template using Laravel and Blade. Utilized PHPUnit for unit testing to ensure the integrity of core functionalities. I integrated Tailwind CSS to create a responsive user interface and used Git for version control, following a feature branch workflow.",
    },
  ],
  educationalExperiences: [
    {
      id: "edu_1",
      icon: DiamondLgPink,
      course: "Java (Basic)",
      institution: "HackerRank",
      degree: "Diploma",
      startDate: "Ian 2025",
      endDate: "Feb 2025",
    },
    {
      id: "edu_2",
      icon: DiamondLgBlue,
      course: "JavaScript Algorithms and Data Structures",
      institution: "freeCodeCamp",
      degree: "Diploma",
      startDate: "Iul 2025",
      endDate: "Sep 2024",
    },
    {
      id: "edu_3",
      icon: DiamondLgGreen,
      course: "Responsive Web Design",
      institution: "freeCodeCamp",
      degree: "Diploma",
      startDate: "Iul 2025",
      endDate: "Sep 2024",
    },
    {
      id: "edu_4",
      icon: DiamondLgOrange,
      course: "The AI Era in Software Development",
      institution: "NetRom Software Academy",
      degree: "Diploma",
      startDate: "Oct 2024",
      endDate: "Dec 2024",
    },
    {
      id: "edu_5",
      icon: DiamondLgYellow,
      course: "Fundamentals of web application",
      institution: "Endava For Students",
      degree: "Diploma",
      startDate: "Feb 2024",
      endDate: "Apr 2024",
    },
    {
      id: "edu_6",
      icon: DiamondLgPink,
      course: "Java",
      institution: "Remote Learning Nagarro",
      startDate: "Nov 2023",
      endDate: "Mar 2024",
    },
    {
      id: "edu_7",
      icon: DiamondLgBlue,
      course: "Embedded Systems",
      institution: "Continental Sibiu",
      degree: "Diploma",
      startDate: "Mar 2023",
      endDate: "May 2023",
    },
    {
      id: "edu_8",
      icon: DiamondLgOrange,
      course: "Computers Science",
      institution: "The Faculty of Automation, Computers and Electronics",
      degree: "Bachelor’s Degree",
      startDate: "Oct 2021",
      endDate: "May 2025",
    },
    {
      id: "edu_9",
      icon: DiamondLgGreen,
      course: "Matematics and computer science,",
      institution:
        "Nicolae Titulescu (High School)",
      degree: "Baccalaureate Diploma",
      startDate: "Sep 2017",
      endDate: "Iun 2021 ",
    },
  ],
  skills: [
    {
      id: "skill_1",
      icon: SkillJavaSpringBoot,
      name: "Java Spring Boot",
      description: "UI Design, Protoyping",
    },
    {
      id: "skill_2",
      icon: SkillAsp,
      name: "ASP .NET Core",
      description: "Hypertext Markup",
    },
    {
      id: "skill_3",
      icon: SkillLaravel,
      name: "Laravel",
      description: "Adobe Tool for UI Design",
    },
    {
      id: "skill_4",
      icon: SkillEntity,
      name: "Entity Framework",
      description: "Picture Edit & Transformation",
    },
    {
      id: "skill_5",
      icon: SkillBlazor,
      name: "Blazor",
      description: "UI Design & Prototyping",
    },
    {
      id: "skill_6",
      icon: SkillTrello,
      name: "Trello",
      description: "Project Management Knowledge",
    },
    {
      id: "skill_7",
      icon: SkillReact,
      name: "React",
      description: "Attractive Design & Frameworks",
    },
    {
      id: "skill_8",
      icon: SkillHtml5,
      name: "HTML5",
      description: "Creating wireframes prior to design",
    },
    {
      id: "skill_9",
      icon: SkillCss,
      name: "CSS",
      description: "Adobe Tool for UI Design",
    },
    {
      id: "skill_10",
      icon: SkillTailwind,
      name: "Tailwind",
      description: "Adobe Tool for UI Design",
    },
    {
      id: "skill_11",
      icon: SkillBootstrap,
      name: "Bootstrap",
      description: "Adobe Tool for UI Design",
    },
    {
      id: "skill_12",
      icon: SkillMicrosoftSQL,
      name: "Microsoft SQLServer",
      description: "Adobe Tool for UI Design",
    },
    {
      id: "skill_12",
      icon: SkillPHPUnit,
      name: "PHPUnit",
      description: "Adobe Tool for UI Design",
    },
    {
      id: "skill_12",
      icon: SkillSelenium,
      name: "Selenium",
      description: "Adobe Tool for UI Design",
    },
    {
      id: "skill_13",
      icon: SkillPostgreSQL,
      name: "PostgreSQL",
      description: "Adobe Tool for UI Design",
    },
  ],
  certificatesAndAwards: [
    {
      id: "cert_award_1",
      icon: Coursera,
      provider: "Coursera",
      course: "UI/UX Advance Course",
      startDate: "Dec 2021",
      endDate: "Feb 2022",
    },
    {
      id: "cert_award_2",
      icon: Google,
      provider: "Google",
      course: "Google UX Design Professional Certificate",
      startDate: "Mar 2021",
      endDate: "Jun 2021",
    },
    {
      id: "cert_award_3",
      icon: Udemy,
      provider: "Udemy",
      course: "Fundamental of UI/UX for Students",
      startDate: "Jun 2020",
      endDate: "Sept 2020",
    },
  ],
  hobbiesAndInterests: [
    {
      id: "hob_1",
      icon: Reading,
      name: "Reading",
    },
    {
      id: "hob_2",
      icon: Travelling,
      name: "Travelling",
    },
    {
      id: "hob_3",
      icon: Blogging,
      name: "Blogging",
    },
  ],
  managementAndLidershipSkills: [
    {
      id: "skill_manage_1",
      icon: DiamondLgPink,
      name: "Communication",
    },
    {
      id: "skill_manage_2",
      icon: DiamondLgYellow,
      name: "Planning and organizing",
    },
    {
      id: "skill_manage_3",
      icon: DiamondLgBlue,
      name: "Strategic decisions",
    },
  ],
  communicationAndInterpersonalSkills: [
    {
      id: "skill_communication_1",
      icon: DiamondLgPink,
      name: "Listening",
    },
    {
      id: "skill_communication_2",
      icon: DiamondLgYellow,
      name: "Teamwork",
    },
    {
      id: "skill_communication_3",
      icon: DiamondLgBlue,
      name: "Public speaking",
    },
  ],
};

export default DATA;
