import {
  Blogging,
  CompanyLogo1,
  Coursera,
  DiamondLgBlue,
  DiamondLgGreen,
  DiamondLgOrange,
  DiamondLgPink,
  DiamondLgYellow,
  Gaming,
  Google,
  Reading,
  SkillCss,
  SkillFigma,
  SkillHtml5,
  SkillPhotoshop,
  SkillSketch,
  SkillTrello,
  SkillWireframe,
  SkillXd,
  Travelling,
  Udemy,
} from "../assets/image";

const DATA = {
  professionalExperiences: [
    {
      id: "prof_exp_1",
      startDate: "Jun 2024",
      endDate: "",
      position: "Junior Web Developer",
      diamondColors: ["Purple", "Yellow", "Blue"],
      company: {
        logo: CompanyLogo1,
        name: "AMC WebSoft",
        info: "Custom website and software development in Craiova, Dolj",
      },
      description:
        "Created a template using Laravel and Blade. Utilized PHPUnit for unit testing to ensure the integrity of core functionalities. Later, I migrated the front end to React. I integrated Tailwind CSS to create a responsive user interface and used Git for version control, following a feature branch workflow.",
    },
  ],
  educationalExperiences: [
    {
      id: "edu_1",
      icon: DiamondLgPink,
      course: "Java (Basic)",
      institution: "HackerRank",
      degree: "Diploma",
      startDate: "Ian 2025",
      endDate: "Feb 2025",
    },
    {
      id: "edu_2",
      icon: DiamondLgBlue,
      course: "JavaScript Algorithms and Data Structures",
      institution: "freeCodeCamp",
      degree: "Diploma",
      startDate: "Iul 2025",
      endDate: "Sep 2024",
    },
    {
      id: "edu_3",
      icon: DiamondLgGreen,
      course: "Responsive Web Design",
      institution: "freeCodeCamp",
      degree: "Diploma",
      startDate: "Iul 2025",
      endDate: "Sep 2024",
    },
    {
      id: "edu_4",
      icon: DiamondLgOrange,
      course: "The AI Era in Software Development",
      institution: "NetRom Software Academy",
      degree: "Diploma",
      startDate: "Oct 2024",
      endDate: "Dec 2024",
    },
    {
      id: "edu_5",
      icon: DiamondLgYellow,
      course: "Fundamentals of web application",
      institution: "Endava For Students",
      degree: "Diploma",
      startDate: "Feb 2024",
      endDate: "Apr 2024",
    },
    {
      id: "edu_6",
      icon: DiamondLgPink,
      course: "Java",
      institution: "Remote Learning Nagarro",
      degree: "",
      startDate: "Nov 2023",
      endDate: "Mar 2024",
    },
    {
      id: "edu_7",
      icon: DiamondLgBlue,
      course: "Embedded Systems",
      institution: "Continental Sibiu",
      degree: "Diploma",
      startDate: "Mar 2023",
      endDate: "May 2023",
    },
    {
      id: "edu_7",
      icon: DiamondLgBlue,
      course: "Embedded Systems",
      institution: "Continental Sibiu",
      degree: "Diploma",
      startDate: "Mar 2023",
      endDate: "May 2023",
    },
    {
      id: "edu_6",
      icon: DiamondLgBlue,
      course: "Information Technology Software",
      institution:
        "Belarusian State University of Informatics and Radioelectronics",
      degree: "Bachelor Degree",
      startDate: "2011",
      endDate: "2015 ",
    },
  ],
  skills: [
    {
      id: "skill_1",
      icon: SkillFigma,
      name: "Figma",
      description: "UI Design, Protoyping",
    },
    {
      id: "skill_2",
      icon: SkillHtml5,
      name: "HTML5",
      description: "Hypertext Markup",
    },
    {
      id: "skill_3",
      icon: SkillCss,
      name: "CSS",
      description: "Attractive Design & Frameworks",
    },
    {
      id: "skill_4",
      icon: SkillPhotoshop,
      name: "Adobe Photoshop",
      description: "Picture Edit & Transformation",
    },
    {
      id: "skill_5",
      icon: SkillSketch,
      name: "Sketch",
      description: "UI Design & Prototyping",
    },
    {
      id: "skill_6",
      icon: SkillTrello,
      name: "Trello",
      description: "Project Management Knowledge",
    },
    {
      id: "skill_7",
      icon: SkillWireframe,
      name: "Wireframing",
      description: "Creating wireframes prior to design",
    },
    {
      id: "skill_8",
      icon: SkillXd,
      name: "Adobe XD",
      description: "Adobe Tool for UI Design",
    },
  ],
  certificatesAndAwards: [
    {
      id: "cert_award_1",
      icon: Coursera,
      provider: "Coursera",
      course: "UI/UX Advance Course",
      startDate: "Dec 2021",
      endDate: "Feb 2022",
    },
    {
      id: "cert_award_2",
      icon: Google,
      provider: "Google",
      course: "Google UX Design Professional Certificate",
      startDate: "Mar 2021",
      endDate: "Jun 2021",
    },
    {
      id: "cert_award_3",
      icon: Udemy,
      provider: "Udemy",
      course: "Fundamental of UI/UX for Students",
      startDate: "Jun 2020",
      endDate: "Sept 2020",
    },
  ],
  hobbiesAndInterests: [
    {
      id: "hob_1",
      icon: Gaming,
      name: "Gaming",
    },
    {
      id: "hob_2",
      icon: Reading,
      name: "Reading",
    },
    {
      id: "hob_3",
      icon: Travelling,
      name: "Travelling",
    },
    {
      id: "hob_4",
      icon: Blogging,
      name: "Blogging",
    },
  ],
};

export default DATA;
